### ISSUE TITLE
julia-repl-buffer: Symbol’s function definition is void: aif

### ISSUE THREAD

**Issue by nbecker** [tpapp/julia-repl#1]
Just tried on emacs-25.1
On M-x julia-repl, I got:
julia-repl-buffer: Symbol’s function definition is void: aif

I did not deactivate ESS, if that matters

**Comment by tpapp** [comment]
Missed a dependency. Latest master (f260be2) should fix it, can you try pulling from master?

**Comment by nbecker** [comment]
I just did git pull, Now I get:
(Spacemacs) Error in dotspacemacs/user-config: Cannot open load file: No such file or directory, anaphora

Skipping check for new version (reason: dotfile)
Loading /home/nbecker/.emacs.d/.cache/recentf...done
Open the quickhelp.
Acc.jl has auto save data; consider M-x recover-this-file
Finding all versions of R on your system...
Sorry, no version of R could be found on your system.
[yas] Reloaded everything (snippets will load just-in-time)....
Quit [2 times]
Loading /home/nbecker/julia-repl/julia-repl.el (source)...
eval-buffer: Cannot open load file: No such file or directory, anaphora

**Comment by nbecker** [comment]
After installing anaphora, now I got:
could not find screen
Symbol’s value as variable is void: term-raw-map

**Comment by tpapp** [comment]
That's curious. What does `C-h v term-raw-map` say? It should be autoloaded. In any case, in the latest version I added a `require`.

Also, if you install screen, it will be used automatically. The message is just a warning.

Thanks for your patience, I am new to packaging in Emacs.

**Comment by tpapp** [comment]
I believe that the latest version should work fine. If not, please open another issue.
