### ISSUE TITLE
julia-repl-send-buffer does not prompt for eterm-color

### ISSUE THREAD

**Issue by antoine-levitt** [tpapp/julia-repl#101]
I usually do not invoke julia-repl with `julia-repl` but instead with `julia-repl-send-buffer`. On installing on a new computer, that resulted in no color for my julia sessions. Running `julia-repl` prompted me for installation and compilation of eterm-color, after which I got color in my REPLs. My guess is that whatever code path is run by `julia-repl` to check for eterm-color isn't run by julia-repl-send-buffer. I  have `(add-hook 'term-mode-hook #'eterm-256color-mode)` in my .emacs.

**Comment by tpapp** [comment]
Can you confirm that this is still an issue with recent master? I just merged #84 which has a different logic. If the issue is still there I will look into it --- please provide Emacs version and your julia-repl & related customization from your init file.

**Comment by antoine-levitt** [comment]
It's tricky because I would have to uninstall eterm-color, which I'm not 100% sure how to do. Let's close this for now, will reopen if I reencounter.
