### ISSUE TITLE
Change in stacktrace output removes ability to find file from error output

### ISSUE THREAD

**Issue by rjpower4** [tpapp/julia-repl#106]
## System information
- Emacs Version: `27.2`
- Julia Version: `1.6.0`
- Julia REPL Version: `latest master`

## Overview of Issue
As seen [here](https://julialang.org/blog/2021/03/julia-1.6-highlights/#improved_stacktrace_formatting), in Julia `v1.6.0` the stacktrace output has been overhauled. 

Here's an example of the old way:
![Screenshot from 2021-04-05 17-13-37](https://user-images.githubusercontent.com/25042796/113628062-5b58a780-9632-11eb-80e1-cc3b88f33087.png)

And the new way:
![Screenshot from 2021-04-05 17-15-43](https://user-images.githubusercontent.com/25042796/113628236-965adb00-9632-11eb-9d83-11d218e2f8f1.png)

Consequently, when in a REPL session in Emacs, the new file location format, i.e. `@ Main ~/path/to/file:<LINENUM>`, no longer permits finding the file by clicking/pressing return on the path. Forgive my ignorance as I'm not sure if this is something that is decided here in the `julia-repl` package or elsewhere, but from my basic understanding this is dictated by the `julia-repl--compilation-regexp-alist`?

**Comment by tpapp** [comment]
Thanks for the bug report. Your understanding is correct. I made a fix in #107, if you can test it it would be helpful.

**Comment by rjpower4** [comment]
Works like a charm for me! Thanks!

**Comment by tpapp** [comment]
Thanks for testing, I will merge that then.
