### ISSUE TITLE
Feature wish: make display-buffer uppon send-string optional

### ISSUE THREAD

**Issue by hexaeder** [tpapp/julia-repl#108]
Thanks for providing this packes, best way to intract with the repl :)

However I'd like to propose a feature idea: since i have two monitors i'd like to have the repl buffer sitting in another emacs frame on another monitor. It would be great to have an optional setting to make the the `display-buffer` call optional in all of the repl interactions (i am a total elisp noob but i guess this function is the culprit).

One might even automate this by checking, whether the julia buffer is allready on display in any other frame.

**Comment by hexaeder** [comment]
I just found out that `pop-to-buffer` respects other `display-buffer` machinery and i can get the desired behavior by setting
```elisp
(setq display-buffer-base-action '(display-buffer-reuse-window (reusable-frames . 0)))
```
see https://emacs.stackexchange.com/questions/64279/pop-to-buffer-in-other-frame-if-file-is-already-visited

**Comment by tpapp** [comment]
Thanks for sharing the solution.
