### ISSUE TITLE
Byte compile warning: define-minor-mode argument form

### ISSUE THREAD

**Issue by tecosaur** [tpapp/julia-repl#113]
Currently in `julia-repl.el` positional arguments are used to define the minor mode, however for a while now `define-minor-mode` has been asking for keyword arguments (`(define-minor-mode MODE DOC [KEYWORD VAL ... &rest BODY])`).

```
julia-repl.el: Warning: Use keywords rather than deprecated positional arguments to `define-minor-mode'
```

**Comment by apatry** [comment]
I had the same message and created this PR to address it:

https://github.com/tpapp/julia-repl/pull/116
