### ISSUE TITLE
Evaluate whole buffer with `include`

### ISSUE THREAD

**Issue by mauro3** [tpapp/julia-repl#12]
It would be great if a buffer, at least when it corresponds to a file, would be evaluated with an `include`.  Otherwise, the REPL history gets cluttered with lots of stuff and I get dizzy from all the stuff scrolling past.

Last, if there is an error it would be clear as it does not get burried.

**Comment by tpapp** [comment]
This is a great idea. What do you think about the following:
1. `C-c C-b` evaluates with `include`,
2. `C-u C-c C-b` sends the buffer as it does now?

**Comment by tpapp** [comment]
@mauro3: The `buffer-include` branch now has a (proposed) fix for this. By default, it will check if the buffer is modified, then prompt about saving it, then use `include`. Can you give me some feedback if this is what you want? I use [Revise.jl](https://github.com/timholy/Revise.jl) so I do not use this feature frequently, so I am wondering if I picked a sensible behavior.

**Comment by mauro3** [comment]
Thanks! I also use Revise, but to just run some script this is still useful.

The problem is that it wants to use `~` for my home, which Julia doesn't understand.  Can you replace that with `$(homedir())`?

**Comment by tpapp** [comment]
Sorry, I don't understand — there is no `~` in my code. Can you send me an Emacs backtrace? (just call `toggle-debug-on-error`, then reproduce the error).

**Comment by mauro3** [comment]
See https://github.com/tpapp/julia-repl/commit/ed434b2b14d1327fa65801f56677e4d497d1f851#commitcomment-25576521

**Comment by tpapp** [comment]
Thanks, a fix is now in the https://github.com/tpapp/julia-repl/tree/paste-mode branch (cf [discussion](https://discourse.julialang.org/t/multiline-input-and-whitespace/7020/5)).

Please give it some testing, then I will merge to master. And probably make a release.

**Comment by mauro3** [comment]
Concerning paste-mode: when hitting C-c C-c again before the last one completed then I get outputs like:
```
julia> using Plots
^[[200~using Parameters
^[[201~
```

**Comment by tpapp** [comment]
That is unavoidable (as far as I can tell), but I documented it in the README. Use `C-RET` (which does not emit these control codes) for stepping through the `using` lines one by one, or `C-c C-c` for the whole region.

**Comment by tpapp** [comment]
Also, made a `0.1.0-alpha` pre-release, thanks for the help!
