### ISSUE TITLE
Does Julia- repl support Startup options with -J for sysimages?

### ISSUE THREAD

**Issue by aminevsaziz** [tpapp/julia-repl#127]
I've searched on how to startup Julia repl with this package using compiled packages using option -J. 
Startup.jl seems like a possible solution for starting Julia with  -Jsysimages.so 
So any suggestions?

**Comment by tpapp** [comment]
See the command line options:

https://github.com/tpapp/julia-repl#switches

**Comment by aminevsaziz** [comment]
> See the command line options:
> 
> https://github.com/tpapp/julia-repl#switches

Thank you. That was quick.
BTW, julia-snail does offer completion using company-capf backend can be implemented in Corfu with some tweaks. This feature is bless for new Julia users. 
So, does have julia-repl have any  future plans for features or it is just supporting Julia.
