### ISSUE TITLE
vterm not available on MS-Windows

### ISSUE THREAD

**Issue by StefanPofahl** [tpapp/julia-repl#130]
When reporting an issue, please provide

1. the Emacs version (`M-x emacs-version [RET]`, will also appear in the buffer `*Messages*`),
independent from emacs version

2. the Julia version (`VERSION`)
independent from Julia version

3. the version of `julia-repl` (something like “latest master” is fine).
“latest master”

5. self-contained steps to replicate the issue.
Installation on a MS-windows computer
see:
https://github.com/akermu/emacs-libvterm

An configuration example for emacs under MS-Windows would be nice.

**Comment by tpapp** [comment]
Sorry, I don't understand why this is an issue with this package. If you don't have `vterm`, just use the other backend.

**Comment by wentasah** [comment]
I think that the example in https://github.com/tpapp/julia-repl#installation-and-loading should work on Windows. It will not use the vterm backend, but the default one. If it doesn't work, tell us which errors you see.

**Comment by wentasah** [comment]
BTW Do you have to use native Windows emacs? vterm should work under WSL.
