### ISSUE TITLE
Good background color?

### ISSUE THREAD

**Issue by linwaytin** [tpapp/julia-repl#139]
1. the Emacs version: 28.2

2. the Julia version: 1.7.3

3. the version of `julia-repl`: latest-master, with `vterm` backend

4. self-contained steps to replicate the issue.
Some of the output or text are hard to read, like [this](https://i.imgur.com/1NjdNd4.png). Can anyone suggest a good color? Or do I miss some configurations?

Thanks.

**Comment by tpapp** [comment]
What theme are you using? I suspect it is not the default. 

Or did you tweak the faces manually? In any case, just <kbd>M-x</kbd> `load-theme` and load something you like.

**Comment by linwaytin** [comment]
It's not default. Maybe I should use the default? 

For now I found if I change the `vterm` background by
```
  (add-hook 'vterm-mode-hook (lambda () (face-remap-add-relative 'default :background "#505050" :foreground "#b0b0b0")))
```
The result seems OK.

**Comment by linwaytin** [comment]
Just checked my theme setup. At least the `spacemacs-light` causes some problem, which makes `julia` use a light gray color in error messages, on a light background.

**Comment by tpapp** [comment]
Closing as it is not related to this package.
