### ISSUE TITLE
FR: show REPL output in LaTeX (if gui) 

### ISSUE THREAD

**Issue by larrasket** [tpapp/julia-repl#143]
It would be great if it had an option to process equations like sagemath `show`

Example: 
![image](https://github.com/tpapp/julia-repl/assets/74098495/a7a913b1-b5d8-42ae-bcc9-7a5f9ab7054c)

**Comment by hexaeder** [comment]
Not sure how this is related to `julia-repl`? I guess first of all you'd need some graphic support in the terminal emulator ([sixel](https://en.wikipedia.org/wiki/Sixel)), which `vterm` does not have afaik :(

On Julia side, one could built something like [`SixelTerm.jl`](https://github.com/eschnett/SixelTerm.jl) to overload show methods for symbolic equations. [`Symbolics.jl`](https://github.com/JuliaSymbolics/Symbolics.jl) already supports latex output, and [`MathTeXEngine.jl`](https://github.com/Kolaru/MathTeXEngine.jl) + CairoMakie could be used to create the bitmaps. So it looks like outside of Emacs all tools required are just waiting to be connected.

**Comment by larrasket** [comment]
The example I provided is from an emacs shell too, see https://github.com/sagemath/sage-shell-mode, however, I'm not sure whether it uses vterm or not. I think that this would be better implemented just by processing any latex-formatted output like the way Org-mode does it, without interpolating the Julia REPL itself.
