### ISSUE TITLE
Feature request: support Eat as terminal backend

### ISSUE THREAD

**Issue by berquist** [tpapp/julia-repl#145]
Eat (https://codeberg.org/akib/emacs-eat) is a new terminal emulator package that brings the benefits of vterm over ansi-term while still being native (no dependency on an external compiled library).  Snail supports it and it works well.

**Comment by tpapp** [comment]
Yes, it looks nice, a PR would be welcome.  Just implement the 3 functions that each backend needs. You may want to wait for https://codeberg.org/akib/emacs-eat/issues/100 to get merged though.

**Comment by tpapp** [comment]
Fixed by #148.
