### ISSUE TITLE
`could not capture basedir` when launching Julia under nsys profiler

### ISSUE THREAD

**Issue by hexaeder** [tpapp/julia-repl#149]
I put the following code in my config to launch julia with the external nsys profiler. 
```emacs-lisp 
 (setq julia-repl-executable-records
        '((default "julia")                  ; in the executable path
          (nsys "nsys launch --trace=cuda julia")))
```
However when I switch to `nsys` it and try to open a repl i just get the error
```
 Warning (emacs): could not capture basedir for Julia executable nil
```

Any idea whats causing the error? `nsys launch --trace=cuda julia` in vterm buffer works just fine...

**Comment by tpapp** [comment]
The capture code just runs
```julia
print("OK" * normpath(joinpath(VERSION <= v"0.7-" ? JULIA_HOME : Sys.BINDIR, Base.DATAROOTDIR, "julia", "base")))
```
Just paste that to the REPL and then add the output here please.

**Comment by hexaeder** [comment]
```julia-repl
julia> print("OK" * normpath(joinpath(VERSION <= v"0.7-" ? JULIA_HOME : Sys.BINDIR, Base.DATAROOTDIR, "julia", "base")))
OK/home/hw/.julia/juliaup/julia-1.11.1+0.x64.linux.gnu/share/julia/base
```
looks like that for me. However, I could solve the problem wrapping the command in a bash script
```
#!/bin/bash
nsys launch --trace=cuda julia --color=yes "$@"
```
which works just fine as an executable record.

**Comment by tpapp** [comment]
Interesting, that does look OK.

I added some debug information to the master branch, can you try starting julia-repl again with that version, and tell me what it prints to the `*Messages*` buffer?

**Comment by hexaeder** [comment]
Sure thing, it printed `Julia basedir query returned “zsh:1: command not found: --history-file=no`

**Comment by tpapp** [comment]
This means that Julia was not started at all. I am not familiar with the `nsys` command, but perhaps you need to quote arguments to the executable, or pass them on another way.

**Comment by hexaeder** [comment]
Hm I think the problem is that 

https://github.com/tpapp/julia-repl/blob/bb90cc1fceccc8dfd0e4b60d624271e4aca6b9b8/julia-repl.el#L425-L428

tries to find the executable path. Which fails if the command is not just a single command. For example
```elisp
(let ((executable "julia"))
    (if (file-name-absolute-p executable)
        executable
      (executable-find executable)))
```
works while
```elisp
(let ((executable "stdbuf -oL -eL julia"))
    (if (file-name-absolute-p executable)
        executable
      (executable-find executable)))
```
returns `nil`. (Here I switched the `nsys` for another "wrapper" process commonly available in linux systems). Which also explains why putting the command in a script is a viable solution.

Since it is a weird usecase to put a multi-argument command as an `executable-record` this isn't necessarily a bug, so feel free to just close this issue :)

**Comment by tpapp** [comment]
@hexaeder: would you mind testing #150 to see if it fixes the issue?

**Comment by hexaeder** [comment]
Just tested it, and I can confirm that works for me now! Thanks for fixing :)
