### ISSUE TITLE
Link with line-breaks don't get created

### ISSUE THREAD

**Issue by mauro3** [tpapp/julia-repl#15]
The links to the source in the errors are not created if there is a line-brake in them.

**Comment by tpapp** [comment]
I know (but thanks for opening an issue). A fix may be possible, but I have to think about it (either fix it in Julia, or in Emacs, eg explore `term-window-width` and `truncate-lines`). Suggestions are of course welcome.

**Comment by tpapp** [comment]
@mauro3: can you please test the branch above? It seems to fix the issue.

**Comment by mauro3** [comment]
Yes, seems to work fine.  A slight wrinkle is that the underlines are longer than the links, but that doesn't matter to me.  Cheers!

**Comment by mauro3** [comment]
Hmm, one thing which I never noticed before now happens: pressing the up-arrow after an error was thrown makes the current prompt and output lines above disappear.

**Comment by tpapp** [comment]
Can't replicate the last one, please provide an MWE and open a separate issue.
