### ISSUE TITLE
VTerm: slow `send-region-or-line` while julia still executing

### ISSUE THREAD

**Issue by hexaeder** [tpapp/julia-repl#151]
When you're sending new code to the repl while julia is still busy, It will take a long time for the "second" command to appear in the repl.

I am not sure if this is a problem with `julia-repl` or with Vterm. I've observed this for a long time now, currently on master for this mode, Julia 1.11 and Emacs 29.4.

# Steps to reproduce:
- mark some of lines which takes a bit to execute (multiple lines, not just a single block)
- call `(julia-repl-send-region-or-line)`
- while julia is still executing the previously run command line by line in the repl,  select another larger block of code and call `julia-repl-send-region-or-line
- after the the first block of commands finishes execution, the second block will start executing. However, the "pasting" into the reply takes forever

https://github.com/user-attachments/assets/47ade412-1081-422b-b859-40703a554e8e

Example from screen recoding:
```julia
# first block to send
sleep(1)
sleep(1)
sleep(1)
sleep(1)

# second block to send
function foo()
    #This is some function with some longish text inside which does nothing but returning a 0.
    #This is some function with some longish text inside which does nothing but returning a 0.
    # ... repeats multiple times
    return 0
end
```

**Comment by tpapp** [comment]
I have not been able to reproduce this (same Emacs and Julia as above, vterm 20241118.1627).

If the issue still persists, you may be able to get more information about what is causing it by inserting `(message ...)` statements in the Elisp code of the relevant functions in julia-repl to see which part is causing the delay.

**Comment by hexaeder** [comment]
Hm interesting. Yes the problem still persists and has so for few years and a few different computers with different OSes. So i kinda assumed it is universion even though depending on peoples workflow you might never hit it.
Maybe I should look into the `vterm` module of doom emacs, which I am using, which might do something special when it comes to vterm settings...

**Comment by hexaeder** [comment]
Funny, I was able to reproduce the problem [outside of emacs](https://discourse.julialang.org/t/julia-repl-pasting-code-while-repls-is-busy-is-slow/123765) so I'll close this issue here.

**Comment by tpapp** [comment]
Thanks for looking into this and getting back here!
