### ISSUE TITLE
More colors

### ISSUE THREAD

**Issue by mauro3** [tpapp/julia-repl#16]
It would be good to have more colors.  For instance `@code_warntype` does not show any red code.

I did some digging https://github.com/atomontage/xterm-color/issues/2, see also link in the last comment.

**Comment by tpapp** [comment]
I don't have the resources to pursue this, but pull requests are always appreciated.

**Comment by mauro3** [comment]
No probs. And I don't have them either.

**Comment by kadir-gunel** [comment]
@mauro3  @tpapp Hello, I started to use julia-repl recently and discovered that if you use OhMyREPL.jl package inside juli-repl mode and call its color schemes function :  `OhMyREPL.colorschemes()` then you can see which color schemes are supported inside emacs.

**Comment by ffevotte** [comment]
It looks like [eterm-256color](https://github.com/dieggsy/eterm-256color) provides just what's needed here: 256-color support for `term`-based buffers.

So, if MELPA is correctly set up, something like this should be enough (adapt if you're not using `use-package`):
```elisp
(use-package eterm-256color
  :ensure t
  :config
  (add-hook 'term-mode-hook #'eterm-256color-mode))
```
