### ISSUE TITLE
Multiple julia prompt

### ISSUE THREAD

**Issue by giordano** [tpapp/julia-repl#2]
First of all, nice job!

When running `julia-repl` in Emacs 24.5.1 I have the following problem:

![screenshot_20161103_173307](https://cloud.githubusercontent.com/assets/765740/19975299/bb0c6d00-a1eb-11e6-87df-bc417b9d2e40.png)

The prompt appears twice, and deleting characters is even worse: every time you delete a character, the prompt pops out again, it's quite annoying.  No problem in Emacs 25.1, maybe something changed in `term` mode, I'm not familiar with it.

I don't know if you're willing to fix this, I opened this ticket as reference for other people running into the same problem.

**Comment by tpapp** [comment]
I can replicate, but unsure how to fix it without a bit of digging. Suggestions are welcome.

I realize now that even the latest Ubuntu has only Emacs 24, so I guess that fixing this would be nice.

**Comment by tpapp** [comment]
Thinking about it, for someone who installs Julia having an Emacs 25 (at least) is a reasonable expectation. So I am closing the issue. Added instructions for latest Emacs.

**Comment by giordano** [comment]
I stand corrected: I experience the problem also in Emacs 25.1.  This happens with Emacs package provided by Debian, but I don't experience the problem with a self-built binary (the one I tried when I first reported the issue).  At this point, I don't know where the issue lies.

**Comment by tpapp** [comment]
Thanks, I will investigate.

**Comment by tpapp** [comment]
@giordano : Sorry for the delay, I managed to replicate the prompt issue on `25.1`, apparently it is coming from some control character mismatch between the Julia terminal code and what `ansi-term` is willing to accept. Not digging into either one of those further, I now use `screen` as a workaround. Hope this fixes the issue for you.

**Comment by tpapp** [comment]
@giordano: Digging into it a bit deeper, I found that `ansi-term` does not handle `\E[G`, which is issued by the Julia's [Base.Terminals.cmove_col](https://github.com/JuliaLang/julia/blob/master/base/Terminals.jl#L116). It looks like this will be fixed in Emacs, see [this commit](http://git.savannah.gnu.org/cgit/emacs.git/commit/lisp/term.el?id=caa31fcaa2fc7b05e411c8155d7641e7660a735a).

**Comment by giordano** [comment]
I tried with `screen`, it seems to do the trick.  Thanks!

**Comment by antoine-levitt** [comment]
Can confirm this is fixed in current emacs master. Is there any other reason to use screen?

(thanks for this mode!)

**Comment by giordano** [comment]
Probably when I said that there was no problem in Emacs 25.1 I actually tested it on Emacs master, but the fix mentioned by Tamas didn't make its way into 25.1.  I tested again on master, and can confirm that works for me there as well.

**Comment by tpapp** [comment]
@antoine-levitt : not really. I will probably replace `screen` with `tmux` and make it optional, allowing connections to remote processes, once the fix makes it into a released Emacs.

**Comment by tpapp** [comment]
The branch [fix-terminal-escapes](https://github.com/tpapp/julia-repl/tree/fix-terminal-escapes) attempts to work around the issue. Testing is appreciated. It looks like the fix above won't make it in to 25.2, so this is needed.

**Comment by tpapp** [comment]
@antoine-levitt : the branch also removes dependence on `screen`.

**Comment by tpapp** [comment]
Merged the experimental branch, closing the issue.

**Comment by giordano** [comment]
Seems to work on both Emacs 25 and 24.  Thank you so much!
