### ISSUE TITLE
julia-repl does not launch in Windows 7

### ISSUE THREAD

**Issue by AnttiSim** [tpapp/julia-repl#20]
I don't seem to get this work with Windows. M-x julia-repl produces an error message: Spawning child process: Invalid argument. A Julia buffer will open (not visibly, but you will find it in buffer list), but it is totally empty.

I have also tried to use ess and julia-shell in Windows without much success.

Emacs version is 25.3.1 and Julia version is 0.6.2. I have the latest master of julia-repl.

I attached my .emacs as emacs.txt.
[emacs.txt](https://github.com/tpapp/julia-repl/files/1575109/emacs.txt)

Cheers!

**Comment by tpapp** [comment]
When you try it in the terminal, does `julia` run?

**Comment by AnttiSim** [comment]
Yes, terminal works fine.

**Comment by tpapp** [comment]
Can you `toggle-debug-on-error` and paste the backtrace here?

**Comment by AnttiSim** [comment]
*Messages* buffer just gives this line:

apply: Spawning child process: Invalid argument

Is this what you meant?

**Comment by tpapp** [comment]
No. If you `M-x toggle-debug-on-error` in Emacs, the error will give a detailed backtrace. That's what would help me figure out what is going on.

**Comment by AnttiSim** [comment]
Ok, I got it. I did just that, but nothing happened. Perhaps that message is not a proper Emacs error message.

**Comment by tpapp** [comment]
I find it hard to debug this as I don't have Windows, but if you eval (ie `M-:`)
```elisp
(make-term "*MYJULIA*" "julia")
```
do you get a buffer name `**MYJULIA**` (it won't be raised, but will show up in `C-x b`), with a running Julia process?

**Comment by AnttiSim** [comment]
Yes, buffer named **MYJULIA** now shows in the list. The buffer itself has no content.

**Comment by tpapp** [comment]
Then I guess it is somehow having trouble finding the executable. Can you try with the full path of your Julia executable as the last argument?

**Comment by AnttiSim** [comment]
I tried this:

(make-term "*MYJULIA*" "c:/Users/AnttiSim/AppData/Local/Julia-0.6.2/bin/julia.exe")

The result was the same still.

**Comment by tpapp** [comment]
I am running out of ideas here, but can you try running something else, eg
```elisp
(make-term "something" "path to some executable on your system")
```
I cannot give more specific help as I don't have Windows. Anything with a command line interface will do, that also runs in a terminal.

**Comment by AnttiSim** [comment]
That did not work either! The result was the same message of invalid argument while spawning child process. I tried it with R, which launches fine with ESS.

Windows would not be my choice either, but I'm kind of forced to use it. As a workaround I now edit julia files with emacs but execute them with Jupyter notebook.

**Comment by tpapp** [comment]
Then I guess this is a problem outside `julia-repl`. Sorry but I have no idea what it could be. You could try without a config file (`emacs -q`), then if that works, bisect it. But I see nothing obviously problematic there. You can also ask on StackOverflow.

Since I don't think this is a `julia-repl` issue, I am closing. If you still find that this issue is specific to this code, please comment here and I will reopen.

**Comment by fleimgruber** [comment]
For reference, the reason is explained [here](https://stackoverflow.com/a/20317860).

**Comment by tpapp** [comment]
@fleimgruber : I am now confused, because after the UPDATE: it says that it should work.

**Comment by fleimgruber** [comment]
Ah well, I should have written instead that this is the reason it does not work on non-cygwin Emacsen? I assumed that @AnttiSim was using a non-cygwin Emacs.

**Comment by tpapp** [comment]
Reopening this issue for @PetrKryslUCSD.

I am not using Windows so I need some help from Windows users to figure it out. Ideally, it would be great to document what ports of Emacs work with `ansi-term`, and put those in the README.

My understanding is that `M-x term` is sufficient to replicate the issue, so one can test without `julia-repl`.

**Comment by PetrKryslUCSD** [comment]
I'm convinced  at this point that the problems have perhaps little to do with julia-repl.

I downloaded a fresh distribution, emacs-26.2-x86_64. I ran `M-x term`: The prompt indicated the program to run, `C:/Users/PK/Downloads/emacs-26.2-x86_64/libexec/emacs/26.2/x86_64-w64-mingw32/cmdproxy.exe`. Running this program results in the error shown at the bottom.

I also tried running `eshell`: it runs. However, trying to bring up Julia leads to a weirdly misbehaved window: the input typed in is not echoed, but Julia produces output.
![image](https://user-images.githubusercontent.com/9855832/69260447-33dd7800-0bc0-11ea-9cd1-a795990179ab.png)

Error when starting term:
![image](https://user-images.githubusercontent.com/9855832/69260061-8b2f1880-0bbf-11ea-9c86-ad96b55ef3b1.png)

**Comment by PetrKryslUCSD** [comment]
Attempting to start julia-repl:
![image](https://user-images.githubusercontent.com/9855832/69261965-e44c7b80-0bc2-11ea-81e9-60c3f2e44891.png)

**Comment by tpapp** [comment]
Yes, I don't think that this has to do anything with `julia-repl`, but nevertheless it would be nice to mention this in the README for Windows users, especially if we can document that it works for *some* versions of Emacs on Windows.

In the discussion thread you mention Cygwin, if you can confirm that it works please provide details.

**Comment by tpapp** [comment]
Things should work with Cygwin now, see also #74.
