### ISSUE TITLE
Multiple Julia prompt (again)

### ISSUE THREAD

**Issue by ablaom** [tpapp/julia-repl#25]
I am running Emacs 25.3.2 on Ubuntu 16.04.4 and am getting the issue reported in this closed [issue](https://github.com/tpapp/julia-repl/issues/2).  Julia version is 0.5.2.  Version of `julia-repl` is latest on master branch.
I open a new file "junk.jl", type a number (say 42) and hit control-return to evaluate and the repl appears with the multiple prompts.

**Comment by ablaom** [comment]
Interestingly, when I use Julia 0.6.2 the problem disappears.

**Comment by tpapp** [comment]
Since Julia `v0.5.*` is not supported (`v0.7` is around the corner), I won't keep workarounds for it. Just use `v0.6.2`.

**Comment by ablaom** [comment]
No worries. Thanks for responding. 

    Anthony Blaom

     It is right it should be so 
Man was made for Joy & Woe 
And when this we rightly know 
Thro the World we safely go 
Joy & Woe are woven fine 
A Clothing for the soul divine 
Under every grief & pine 
      Runs a joy with silken twine 

      - from Blake’s Auguries of Innocence
