### ISSUE TITLE
working directory

### ISSUE THREAD

**Issue by tpapp** [tpapp/julia-repl#29]
When 

1. starting a new inferior Julia process,
2. and the current buffer is a julia file,

use the directory of that file as the working directory.

cf [this discussion](https://github.com/syl20bnr/spacemacs/pull/10444#issuecomment-401604575)

**Comment by tpapp** [comment]
Fixed on the `dev` branch, will merge that when other v0.7 bugs are fixed.

**Comment by tpapp** [comment]
It is not going to be that easy, still WIP.

**Comment by gdkrmr** [comment]
wouldn't it be easier to implement this in `julia-mode`, I am pretty ignorant about the internals so forgive me if I am wrong. If a buffer in `julia-mode` is not associated with any `repl`, simply start one and change the path to the directory of the file associate with the buffer, if it is inside a package/project, change the path to the package/project root. If it is a `projectile` project you may also want to consider changing the path to the projectile root. I think that `ESS` is doing something similar with `R` packages.

**Comment by gdkrmr** [comment]
Looking for something like `Project.toml` is pretty easy:
```elisp
(defun julia-repl-get-package-root ()
  (interactive)
  (message
   (locate-dominating-file (buffer-file-name) "Project.toml")))
```

**Comment by tpapp** [comment]
There are two questions related to this issue:

1. What should the path be? If the user is editing `something/Foo/src/Foo.jl`, should one use the project root `something/Foo/`, or the directory of the file, eg `something/Foo/src/`? IMO the latter is more useful when running code interactively, as it makes `include` work as intended.

2. How to communicate this to `make-term` when opening a new terminal? This is an implementation question I need to explore, for some reason setting `default-directory` does not seem to be enough.

**Comment by gdkrmr** [comment]
> If the user is editing something/Foo/src/Foo.jl, should one use the project root something/Foo/, or the directory of the file, eg something/Foo/src/? IMO the latter is more useful when running code interactively, as it makes include work as intended.

I would say that in the future with `Revise.jl` the path should be `/something/Foo/`. In the case that you are working on a file outside of a project, there should be a configurable variable such, i.e. `julia-repl-no-project-default-folder`, which could be `"."` for the current folder, `"~"` for `$HOME`, or point to any other folder.

> How to communicate this to make-term when opening a new terminal? This is an implementation question I need to explore, for some reason setting default-directory does not seem to be enough.

Just send a `cd(...)` to the terminal after opening and before any other command, forgive my ignorance if this is not a simple thing to do?
