### ISSUE TITLE
Set environmental variables for started process

### ISSUE THREAD

**Issue by Paethon** [tpapp/julia-repl#31]
I just noticed, that the REPL started using `julia-repl` does not seem to use the environmental variables set in `.bashrc`

Specifically I am setting `export JULIA_NUM_THREADS=4`, but in the REPL started from Emacs `Threads.nthreads()` still reports `1` (It does work when starting the Julia REPL directly from the Terminal)

Any solution for this?

**Comment by tpapp** [comment]
I just use `setenv` in my `init.el`, eg

```lisp
(setenv "JULIA_NUM_THREADS" "4")
```

**Comment by Paethon** [comment]
Perfect, that did it. Thanks :)

**Comment by tpapp** [comment]
I reopened this issue because I will document it for the next release. Thanks for bringing it to my attention.
