### ISSUE TITLE
C-a doesn't move to beginning of line in REPL

### ISSUE THREAD

**Issue by presheaf** [tpapp/julia-repl#4]
It is very useful to be able to go to start of line to fix a minor mistake one does not see before having finished the end of line. Unfortunately, the standard emacs shortcut for doing this is "stolen" by screen, which uses C-a as escape key. Because it doesn't seem important to use the screen escape key much in Julia REPL's in emacs, it would be good to change the escape key to something other than C-a.

**Comment by tpapp** [comment]
The latest version does not use `screen`, since I managed to work around the terminal bug. This was already in a branch, which I just merged.
