### ISSUE TITLE
Error during redisplay: (jit-lock-function 8) signaled (invalid-regexp "Unmatched ) or \\)")

### ISSUE THREAD

**Issue by taqtiqa-mark** [tpapp/julia-repl#47]
Thank you for all the time and effort you have put into making this package available.
Unfortunately I've hit an issue with launching the Julia REPL.  

Possibly related to issue #24

Details follow.

1. the Emacs version (`M-x emacs-version [RET]`, will also appear in the buffer `*Messages*`),

`GNU Emacs 26.1 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.18.9) of 2018-05-29`

2. the Julia version (`VERSION`)

`v1.0.2`

3. the version of `julia-repl` (something like “latest master” is fine).

This version information is quite obscure to discover - hints or tips appreciated

4. self-contained steps to replicate the issue.

`SPC-m-r`

The logo scrolls up until the following prompt is at the top of the buffer displayed:

````
julia> 
 sleep\ 604800\ \&\ sleep\=\$\!\;\ trap\ \"kill\ \$sleep\;\ exit\ 0\"\ USR1\;\ trap\ \"kill\ \$sleep\;\ exit\ 1\"\ USR2\;\ wait\ \$sleep\'
 sleep\ 604800\ \&\ sleep\=\$\!\;\ trap\ \"kill\ \$sleep\;\ exit\ 0\"\ USR1\;\ trap\ \"kill\ \$sleep\;\ exit\ 1\"\ USR2\;\ wait\ \$sleep\'
 sleep\ 604800\ \&\ sleep\=\$\!\;\ trap\ \"kill\ \$sleep\;\ exit\ 0\"\ USR1\;\ trap\ \"kill\ \$sleep\;\ exit\ 1\"\ USR2\;\ wait\ \$sleep\
 sleep\ 604800\ \&\ sleep\=\$\!\;\ trap\ \"kill\ \$sleep\;\ exit\ 0\"\ USR1\;\ trap\ \"kill\ \$sleep\;\ exit\ 1\"\ USR2\;\ wait\ \$sleep
 sleep\ 604800\ \&\ sleep\=\$\!\;\ trap\ \"kill\ \$sleep\;\ exit\ 0\"\ USR1\;\ trap\ \"kill\ \$sleep\;\ exit\ 1\"\ USR2\;\ wait\ \$slee
 sleep\ 604800\ \&\ sleep\=\$\!\;\ trap\ \"kill\ \$sleep\;\ exit\ 0\"\ USR1\;\ trap\ \"kill\ \$sleep\;\ exit\ 1\"\ USR2\;\ wait\ \$sle
 sleep\ 604800\ \&\ sleep\=\$\!\;\ trap\ \"kill\ \$sleep\;\ exit\ 0\"\ USR1\;\ trap\ \"kill\ \$sleep\;\ exit\ 1\"\ USR2\;\ wait\ \$sl
````
etc.
etc.

In Messages buffer:
````
Error during redisplay: (jit-lock-function 8) signaled (invalid-regexp "Unmatched ) or \\)")
Error during redisplay: (jit-lock-function 1) signaled (invalid-regexp "Unmatched ) or \\)")
Error during redisplay: (jit-lock-function 229) signaled (invalid-regexp "Unmatched ) or \\)")
Error during redisplay: (jit-lock-function 43) signaled (invalid-regexp "Unmatched ) or \\)")
Error during redisplay: (jit-lock-function 1) signaled (invalid-regexp "Unmatched ) or \\)")
Error during redisplay: (jit-lock-function 8) signaled (invalid-regexp "Unmatched ) or \\)") [2 times]
````

**Comment by taqtiqa-mark** [comment]
Progress, but have not yet isolated which line caused the error...

In my `.spacemacs` I had:

```
(add-hook 'shell-mode-hook  'with-editor-export-editor)
(add-hook 'term-exec-hook   'with-editor-export-editor)
(add-hook 'eshell-mode-hook 'with-editor-export-editor)
```

Commenting out (`;;`) all three allowed the reply to start.  I don't have history beyond the last command but at least things now progress.

Will update when I've identified one line that can cause the behavior described.

**Comment by tpapp** [comment]
Thanks for the update. I don't know how to fix this but would be happy to include a fix if you discover one.

**Comment by taqtiqa-mark** [comment]
The setting referred to previously arise in the context of using magit and the `with-editor` package.
Some details here.
https://magit.vc/manual/with-editor.html

Still not clear what it is about the `$EDITOR` setting that causes the behavior observed.
