### ISSUE TITLE
CL function use without explicit (REQUIRE 'CL)

### ISSUE THREAD

**Issue by pand5461** [tpapp/julia-repl#56]
The function definitions for `first`, `second`, `incf` and `stable-sort` are void unless `(require 'cl)` is used.

The CL package is loaded by Julia-mode, but when it is not used, the REPL does not start.

**Comment by tpapp** [comment]
Good catch, will fix. Thanks!

**Comment by tpapp** [comment]
I spoke to soon: apparently we already
```emacs-lisp
(require 'cl-lib)
```
which should take care of this, and is AFAIK [the preferred approach](https://www.emacswiki.org/emacs/CommonLispForEmacs).

This would work for everything above Emacs 24.3. Which version are you using?

**Comment by pand5461** [comment]
Emacs 26.1.

`cl-lib` provides the names with the `cl-` prefix. Thus, the names must be `cl-first` etc.

**Comment by tpapp** [comment]
@pand5461: Thanks, I prefixed everything I suspected with `cl-` in #57, but if you have a systematic way of triggering any remaining errors, please let me know if I missed any.

**Comment by pand5461** [comment]
Calling `(byte-compile-file "julia-repl.el")` from `emacs --no-init-file` produces no warnings. I guess, that means there are no implicit dependencies now. Thanks!
