### ISSUE TITLE
Sending "mean_μ = 0" to OhMyREPL with C-c C-c causes it to error

### ISSUE THREAD

**Issue by dalejordan** [tpapp/julia-repl#63]
julia> mean_μ = nothing                                       (sent by C-c C-c, not typed)

julia> ┌ Error: Error in the keymap
│   exception =
│    StringIndexError("mean_μ = 0\n", 7)
│    Stacktrace:
│     [1] (::getfield(OhMyREPL.Prompt, Symbol("##25#51")))(::Any, ::Any, ::Any) at /home/dale/.julia/packages/OhMyREPL/GFHgr/src/repl.jl:189
│     [2] #invokelatest#1 at ./essentials.jl:742 [inlined]
│     [3] invokelatest at ./essentials.jl:741 [inlined]
│     [4] (::getfield(REPL.LineEdit, Symbol("##27#28")){getfield(OhMyREPL.Prompt, Symbol("##25#51")),String})(::Any, ::Any) at /build/julia/src/julia-1.1.0/usr/share/julia/stdlib/v1.1/REPL/src/LineEdit.jl:1324
└ @ REPL.LineEdit /build/julia/src/julia-1.1.0/usr/share/julia/stdlib/v1.1/REPL/src/LineEdit.jl:2367
julia> 

The error is related to the "mu" character; removing it works ok.
Maybe somebody is not expecting unicode?

Emacs 26.2
Julia 1.1.0
julia-repl-20190124.1059

**Comment by tpapp** [comment]
I can replicate this in the terminal outside Emacs (copy-pasting `mean_μ = nothing` directly, not using the `\mu` <kbd>TAB</kbd> expansion), so I don't think this is a bug in `julia-repl`. You may want to open an issue for OhMyREPL instead.

**Comment by dalejordan** [comment]
Done
https://github.com/KristofferC/OhMyREPL.jl/issues/172
