### ISSUE TITLE
julia-repl-send-buffer prints latest executed expression

### ISSUE THREAD

**Issue by mattuntergassmair** [tpapp/julia-repl#65]
Executing `julia-repl-send-buffer` (via `C-c` `C-b`) runs "include(file)" which returns the last evaluated expression (see docs: https://docs.julialang.org/en/v1/base/base/#Base.include) - in many cases, this clutters the REPL. Would it not be better to run "include(file);" instead, suppressing the output with a semicolon?

Replicating the issue (Emacs 26.2, Julia 1.2.0, latest julia-repl):
Save the following text in a julia buffer 

```
a = "Hello World"
b = "foo";
```

`C-c` `C-b` to execute the buffer prints "foo" to the REPL (expected would be no output)

**Comment by tpapp** [comment]
Thanks for the suggestion. It definitely makes sense, I will implement it #66 and will experiment with it for a while, then possibly merge.
