### ISSUE TITLE
Is it possible to do a cycle boot mode like atom?

### ISSUE THREAD

**Issue by jasonsun0310** [tpapp/julia-repl#67]
In Atom, we can have 3 Julia processes at the same time so that if we need to a new REPL, we can always have one immediately without any wait. Is it possible in julia-repl?

**Comment by tpapp** [comment]
You mean like a pool of processes waiting in a queue? It may be possible, but that is currently not implemented. I find startup times to be too trivial for this.

You can run multiple inferior processes, try <kbd>C-c C-s</kbd> which sets a different suffix, and then <kbd>C-c C-z</kbd> will take you there, or start a new process on demand.
