### ISSUE TITLE
Do not echo sent commands in Julia REPL

### ISSUE THREAD

**Issue by scheidan** [tpapp/julia-repl#71]
I'm a happy `julia-repl` user, thanks for the work! From time to time there is one feature I miss from ESS:

Currently every command that is sent, is echoed in the Julia REPL. If a large code region is sent, the julia buffer gets cluttered quickly. So I was wondering if an option exist to not show the commands, only the results.
 
In ESS this behaviour can be obtained by setting `ess-eval-visibly` to `nil`, see [documentation here](http://ess.r-project.org/Manual/ess.html#Evaluating-code).

**Comment by tpapp** [comment]
`julia-repl` operates by simply sending stuff to an ANSI terminal, so unfortunately I don't see a way to avoid echoing. Note that large whole files will be just sent with an `include` by `julia-repl-send-buffer`.

Generally I would recommend Revise.jl for working with larger pieces of code.
