### ISSUE TITLE
Copying from the *julia*

### ISSUE THREAD

**Issue by PetrKryslUCSD** [tpapp/julia-repl#73]
Copying text in the *julia* buffer is not successful. For instance, there is a message in the buffer to install a package. I try to copy `import Pkg; Pkg.add("Revise")` but no go.
I use the latest `julia-repl` and cygwin Emacs 26.

**Comment by PetrKryslUCSD** [comment]
It might be that I have to switch between line-mode and char-mode.

**Comment by tpapp** [comment]
Yes, that's the way to do it. See 

https://github.com/tpapp/julia-repl#interacting-with-term

Do you think it should be documented in more detail?

**Comment by PetrKryslUCSD** [comment]
Sorry, I missed it on first reading. I think the documentation is fine.
