### ISSUE TITLE
mishandling of unicode characters, and \<latex...>

### ISSUE THREAD

**Issue by ko56** [tpapp/julia-repl#77]
1. Emacs version: 26.3

2. Julia version: 1.1.1

3. julia-repl-20191124.1534

4. Type ?range, or type "for i \in 1:10"
You will see \xxx ... instead of properly-displayed characters.

Version 20190908.1717 did not have these problems.

**Comment by tpapp** [comment]
I cannot replicate this.

Does this happen in the Julia code buffer (which is handled by `julia-mode`, and should have nothing to do with this package) or in the terminal?

Can you do a `git bisect` to pin down the commit which broke this for you?

**Comment by ko56** [comment]
The problem is with the code buffer:

julia> for r \342\210\210  eachrow(df)
         haskey(cnt,r.rsrq) || (cnt[r.rsrq] = 0)
         cnt[r.rsrq] += 1
       end

julia> S = 10000.0;  # scale factor

This is with julia-mode-20191108.1436.  Are you saying julia-mode is the problem?  I think in my Emacs I updated both julia-mode and julia-repl at the same time to julia-mode-20191108.1436
and julia-repl-20190908.1717.

**Comment by tpapp** [comment]
> The problem is with the code buffer:

Now I am very confused, because that looks like the REPL (which is indeed managed by `julia-repl`).  Just to clarify:

1. `julia-mode` is what is usually used for *editing* `.jl` files,

2. `julia-repl` is for *interacting with the inferior process*, and has `julia>` prompts etc.

Which one is it?

> Are you saying julia-mode is the problem?

I don't know, because I could not replicate. But bisection would be the best way to answer what, if anything, broke.

**Comment by ko56** [comment]
Sorry, I misunderstood what you meant by "code buffer".  What I posted is indeed from the REPL, managed by julia-repl.

You can't replicate the problem and you have the same julia-mode and julia-repl as I do?
(I'm not familiar with git bisection, but I'll take a look)

**Comment by tpapp** [comment]
I am using latest `master` for both, but that should not make a difference. You could also update to at least the latest MELPA versions.

If that fails, please bisect.

**Comment by ko56** [comment]
The versions I see on MELPA are the same with what I have: julia-mode 20191108.1436 
and julia-repl 20191124.1534.

**Comment by ko56** [comment]
I've been puzzling over this for a while.  I found out the following curious thing: if I ssh into the system and start "emacs -nw" in a shell window, then start julia-repl, I can type in the code buffer (REPL buffer) x \in TAB, and the \in gets transformed to the right symbol.

However, if I am *on* the system, and I start "emacs -nw" in a shell window, I get  \342\210\210 after I hit TAB. Mysterious.

**Comment by ko56** [comment]
Problem fixed.  There must be some interaction between julia-repl and some other Emacs package that I was using. I've eliminated a whole bunch of them from my init.el (that were not useful anyway), and the problem went away.
