### ISSUE TITLE
can't seem to get it to work

### ISSUE THREAD

**Issue by atteson** [tpapp/julia-repl#8]
(require 'julia-repl) fails for me at (require 'dash) on line 42.  I'm running on emacs 25.1.1 on a Mac.

**Comment by atteson** [comment]
I just read the comments that I need to install dash.

**Comment by tpapp** [comment]
I have submitted to MELPA so that installation becomes automatic. Will close the issue when MELPA merges.

**Comment by tpapp** [comment]
@atteson, are you still experiencing problems? If not, I would close the issue.

**Comment by tpapp** [comment]
Closing as I cannot replicate with current version.
