### ISSUE TITLE
DataFrames aren't aligned properly and ? for missing values not displayed

### ISSUE THREAD

**Issue by prosoitos** [tpapp/julia-repl#85]
Emacs 26.3
Julia 1.3.1
julia-repl-20200310.1145

---

This is a minor issue which has more to do with aesthetics than anything else.
DataFrames don't seem to align properly.

Compare:

Emacs julia-repl

![2020-03-18_16:49:50](https://user-images.githubusercontent.com/4634851/77017772-8e050480-6938-11ea-9c95-566dc76768a1.png)

with:

Julia REPL

![2020-03-18_16:49:14](https://user-images.githubusercontent.com/4634851/77017778-92312200-6938-11ea-95e7-3694774d93f3.png)

**Comment by prosoitos** [comment]
Also, I just realized that the `?` which signals the presence of missing values in a column does not show in Emacs:

Emacs julia-repl

![2020-03-18_16:56:28](https://user-images.githubusercontent.com/4634851/77018112-8c880c00-6939-11ea-903f-d37e0c63e506.png)

Julia REPL

![2020-03-18_16:55:30](https://user-images.githubusercontent.com/4634851/77018119-9447b080-6939-11ea-8133-d90986925f87.png)

**Comment by apparluk** [comment]
Emacs 26.3
Julia 1.4.2
julia-repl-1.2.0 (melpa-stable)

GUI and Terminal output are identical.

<hr>

```julia
julia> using DataFrames

julia> df = DataFrame(A = 1:4, B = ["M", "F", "F", "M"])
4×2 DataFrame
│ Row │ A     │ B      │
│     │ Int32 │ String │
├─────┼───────┼────────┤
│ 1   │ 1     │ M      │
│ 2   │ 2     │ F      │
│ 3   │ 3     │ F      │
│ 4   │ 4     │ M      │

julia> DataFrame(a = 1:2, b = [1.0, missing],                                                         
       c = categorical('a':'b'), d = [1//2, missing])                                                 
2×4 DataFrame                                                                                         
│ Row │ a     │ b        │ c    │ d         │                                                         
│     │ Int32 │ Float64? │ Cat… │ Rationa…? │                                                         
├─────┼───────┼──────────┼──────┼───────────┤                                                         
│ 1   │ 1     │ 1.0      │ 'a'  │ 1//2      │                                                         
│ 2   │ 2     │ missing  │ 'b'  │ missing   │                                                         
                                                                                                      
julia> 

```

**Comment by tpapp** [comment]
I think this is an issue the font width hinting. Eg can replicate this with Iosevka's default font, but this does not show up with Iosevka Fixed. Could also be the fallback font. This can be investigated with eg <kbd>M-x</kbd> `describe-char`.

If this shows up in an Emacs running in a terminal, then this may be a julia-repl issue, but otherwise it is just something that should be fixed by using a different font.

**Comment by prosoitos** [comment]
Oh, interesting. OK. Thanks for the tip!!

I guess I should close this issue then?

**Comment by prosoitos** [comment]
> If this shows up in an Emacs running in a terminal, then this may be a julia-repl issue, but otherwise it is just something that should be fixed by using a different font.

It wasn't in the terminal. So it must be the font problem.

**Comment by tpapp** [comment]
Yes, I think it is a font problem. Closing, but feel free to ask here if you think it has to do with julia-repl and I will reopen.
