### ISSUE TITLE
Works great in Linux but 'ctrl-c' commands don't work for me on the Mac

### ISSUE THREAD

**Issue by compleathorseplayer** [tpapp/julia-repl#87]
When reporting an issue, please provide

1. the Emacs version (`M-x emacs-version [RET]`, will also appear in the buffer `*Messages*`),
26.3
2. the Julia version (`VERSION`)
1.4.1
3. the version of `julia-repl` (something like “latest master” is fine).
latest master
4. self-contained steps to replicate the issue.
M-x julia-repl

All looks fine until I try to do something like ctrl-enter to execute code or any 'ctrl c'
Is this a Mac thing, or just me getting lucky?
Is there a fix? [like a line for .emacs    (if so where in the .emacs file to put it?)]

Thanks for any hints.

**Comment by prosoitos** [comment]
I don't think that `C-c` works in term-mode.

Not sure this is a good approach, but what I did is to bind a key of my choice to `term-interrupt-subjob` to kill the running job.

```elisp
(add-hook 'term-mode-hook (lambda ()
			    (define-key term-raw-map (kbd "<key>") 'term-interrupt-subjob)))
```

**Comment by compleathorseplayer** [comment]
Thanks Prosoitos - I think there is a misunderstanding here... I don't need an interrupt, I just would like to use the given commands like ('ctrl-c ctrl-c' to send the current line the the REPL as listed here) but can't get that to work.

**Comment by Nathan-Furnal** [comment]
If you add the hook from the docs it should load julia-repl-mode in any julia mode, and work.

**Comment by Nathan-Furnal** [comment]
You can link a mode with a file extension :

```elisp
(add-to-list 'auto-mode-alist '("\\.jl\\'" . julia-repl-mode))
```
This should open julia-repl-mode in any julia file. 
Alternatively, this in your .emacs

```elisp
(require 'julia-repl)
(add-hook 'julia-mode-hook 'julia-repl-mode) ;; always use minor mode
```
should open the repl anytime ``julia-mode`` starts.

**Comment by compleathorseplayer** [comment]
Hi Thanks.   I already had the second 'hook' section in my .emacs file.   I tried adding the first suggestion (then restarting) and it didn't work either - I still have to start julia-repl-mode manually.
It could have to do with the way  emacs automatically changes the ' and " marks which change their meaning in the .emacs file.

**Comment by Nathan-Furnal** [comment]
That's strange, I'm not using the first line of code I wrote above and yet it still works for me.

When you open a julia file and type 
``M-:`` then ``major-mode`` what does it say?

**Comment by compleathorseplayer** [comment]
julia-mode

**Comment by Nathan-Furnal** [comment]
Alright, what about when you try ``C-h m``? What modes are detected? Do this *before* you use the repl and do not try in a buffer where the repl is already active.

**Comment by compleathorseplayer** [comment]
Hi Nathan,  I got it fixed -  when I had copied lines from a forum to add to the .emacs file, the quotes had changed font (and meaning).  I fixed this and now it works.  
Thanks to you, I knew where to look.
Thanks!

**Comment by Nathan-Furnal** [comment]
Glad it's sorted, have fun!

**Comment by prosoitos** [comment]
Sorry I missed the point @compleathorseplayer :slightly_smiling_face:

**Comment by compleathorseplayer** [comment]
Hi P,  You had (helpfully, I might add) answered a question I wasn't asking - which I think was how to send a control-c to interrupt something running in the REPL.    I just wanted to be able to send commands by typing control-c twice, etc.   What I didn't understand (but was later helped with) was that julia-repl-mode had not started properly in my editing window (the REPL was there, but I couldn't send commands).    You ended up giving me a useful bit of info which I have since used, though!  
Thanks!
