### ISSUE TITLE
Julia-repl would not start on Windows

### ISSUE THREAD

**Issue by PetrKryslUCSD** [tpapp/julia-repl#89]
This is what I get when running M-x julia-repl:
Warning (emacs): could not capture basedir for Julia executable julia

Windows 10, Emacs 26.3

**Comment by PetrKryslUCSD** [comment]
Sorry, I forgot that this was already covered: https://github.com/tpapp/julia-repl/issues/20

**Comment by apparluk** [comment]
@PetrKryslUCSD Since the merging of https://github.com/tpapp/julia-repl/commit/dddc6fd68a26ad3fb706cf59b4d63599a6be6da1 on 22 Jun 2020 does the warning still appear?

**Comment by PetrKryslUCSD** [comment]
I couldn't get the terminal to work well on Windows, and I'm afraid I gave up on it some time ago. Sorry. I think you can close this issue.

**Comment by apparluk** [comment]
> couldn't get the terminal to work well

What about [fakecygpty](https://github.com/d5884/fakecygpty)?

**Comment by tpapp** [comment]
Thanks, closing. If the issue is still relevant please just open a new one.
