### ISSUE TITLE
Support for JuliaFormatter.jl

### ISSUE THREAD

**Issue by TravisBarryDick** [tpapp/julia-repl#92]
I realize that this might be beyond the scope of the julia-repl project, so feel free to say so. Having said that, it would be very nice if there was a way to format the current buffer using https://github.com/domluna/JuliaFormatter.jl. This is one feature of Juno and atom that I've been missing since switching back to emacs for my julia development.

If this seems within the scope of julia-repl, I would be happy to work on an implementation, but I have very limited elisp experience and would need a few pointers to get started probably.

**Comment by tpapp** [comment]
I think this is a neat idea, but I don't think this is within the scope of julia-repl.

I would suggest that this is implemented as an [Emacs minor mode](https://www.gnu.org/software/emacs/manual/html_node/elisp/Defining-Minor-Modes.html). That way, users of various Emacs solutions for Julia can use it independently of their main interface.
