### ISSUE TITLE
Julia always opens in new window

### ISSUE THREAD

**Issue by DanielReedOcean** [tpapp/julia-repl#98]
### Setup
**Emacs:** 27.1 (build 1, x86_64-apple-darwin19.5.0) of 2020-09-04

**Julia**: Version 1.3.1 (2019-12-30)

`julia-repl`: latest master

-----

### Issue
I'm sure this is a PEBKAC issue, but I cannot figure it out. I want to open `julia-repl` in the existing window. Accordingly, in my `init.el` I specify the following:

```
(setq display-buffer-alist
             '(("*R*" (display-buffer-same-window))
               ("*julia*" (display-buffer-same-window))))
```

This works correctly for R – a new window opens for R when omitting this code, but doesn't when I include this code – but Julia _always_ opens in a new window regardless (i.e., `emacs` then `M+x julia-repl` splits the screen to open `Julia`). Why doesn't Julia open in the existing window?

**Comment by tpapp** [comment]
Should be fixed by your #99, thanks! Feel free to reopen if still an issue.
